import { ObjectsPanel } from "./ObjectsPanel"
import { NodeInspector, LineInspector } from "./ToolInspector"
import { DocumentSidebar } from "./DocumentSidebar"
import { useEffect, useRef, useState, type ReactNode } from "react"
import { AlignHorizontalJustifyStart, Group, Ungroup, Layers, CircleHelp, Copy, Download, FilePlus2, FolderOpen, Square, Pencil, Eraser, PaintBucket, Pipette, Hand, Link2, LocateFixed, PanelLeft, MessageSquareText, MousePointer2, Redo2, Save, Trash2, Undo2, X, ZoomIn, ZoomOut } from "lucide-react"
import { type Editor, type EditorSnapshot, type Tool } from "@draw/editor"
import { Button } from "@draw/ui/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@draw/ui/components/ui/dialog"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@draw/ui/components/ui/dropdown-menu"
import { Input } from "@draw/ui/components/ui/input"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@draw/ui/components/ui/tooltip"

const initialSnapshot: EditorSnapshot = { objects: [], selectedEdge: null, drawingCharacter: "#", documents: [], activeDocumentId: "", documentBusy: true, selectedCount: 0, canGroup: false, canUngroup: false, title: "Untitled diagram", tool: "select", selected: null, nodeCount: 0, edgeCount: 0, connections: [], zoom: 1, canUndo: false, canRedo: false, status: "Starting engine…", error: null }
const tools: Array<{ tool: Tool; label: string; key: string; icon: ReactNode }> = [
  { tool: "select", label: "Select", key: "V", icon: <MousePointer2 /> },
  { tool: "pan", label: "Pan", key: "H", icon: <Hand /> },
  { tool: "rectangle", label: "Rectangle", key: "R", icon: <Square /> },
  { tool: "text", label: "Text", key: "T", icon: <MessageSquareText /> },
  { tool: "line", label: "Line", key: "L", icon: <Link2 /> },
  { tool: "pencil", label: "Pencil", key: "P", icon: <Pencil /> },
  { tool: "eraser", label: "Eraser", key: "E", icon: <Eraser /> },
  { tool: "fill", label: "Fill", key: "B", icon: <PaintBucket /> },
  { tool: "picker", label: "Picker", key: "I", icon: <Pipette /> },
]

function TipButton({ label, shortcut, children, ...props }: React.ComponentProps<typeof Button> & { label: string; shortcut?: string }) {
  return <Tooltip><TooltipTrigger render={<Button {...props} aria-label={props["aria-label"] ?? label} />}>{children}</TooltipTrigger><TooltipContent>{label}{shortcut && <kbd>{shortcut}</kbd>}</TooltipContent></Tooltip>
}
export default function App() {
  const hostRef = useRef<HTMLDivElement>(null), editorRef = useRef<Editor | null>(null), fileRef = useRef<HTMLInputElement>(null)
  const sidebarToggle = useRef<HTMLButtonElement>(null), objectsToggle = useRef<HTMLButtonElement>(null)
  const [openPanel, setOpenPanel] = useState<'documents' | 'objects' | null>(() => { try { return localStorage.getItem('draw-sidebar-open') !== 'false' ? 'documents' : null } catch { return 'documents' } })
  const sidebarOpen = openPanel === 'documents', objectsOpen = openPanel === 'objects'
  const togglePanel = (panel: 'documents' | 'objects' | null) => { setOpenPanel(panel); try { localStorage.setItem('draw-sidebar-open', String(panel === 'documents')) } catch {} }
  const toggleSidebar = (open: boolean) => togglePanel(open ? 'documents' : null)
  const closeSidebar = () => { toggleSidebar(false); sidebarToggle.current?.focus() }
  const [renameOpen, setRenameOpen] = useState(false)
  const [snapshot, setSnapshot] = useState(initialSnapshot), [titleDraft, setTitleDraft] = useState(initialSnapshot.title), [dismissedError, setDismissedError] = useState<string | null>(null)
  useEffect(() => { let disposed = false, instance: Editor | undefined; void import("@draw/editor").then(({ Editor }) => { if (disposed || !hostRef.current) return; instance = new Editor(hostRef.current, { onChange: setSnapshot }); editorRef.current = instance; return instance.ready }).catch(error => { if (!disposed) setSnapshot(s => ({ ...s, status: "Engine unavailable", error: error instanceof Error ? error.message : String(error) })) }); return () => { disposed = true; instance?.destroy(); editorRef.current = null } }, [])
  useEffect(() => setTitleDraft(snapshot.title), [snapshot.title]); useEffect(() => { if (snapshot.error !== dismissedError) setDismissedError(null) }, [snapshot.error])
  const editor = () => editorRef.current, commitTitle = () => { const title = titleDraft.trim() || "Untitled diagram"; setTitleDraft(title); editor()?.setTitle(title); setRenameOpen(false) }
  return <TooltipProvider delay={350}><main className="app-shell"><h1 className="sr-only">{snapshot.title}</h1>
    <section className="workspace"><div className="canvas-host" ref={hostRef} />
    <div className="document-library-surface" data-open={openPanel !== null} aria-hidden="true" /><div className="sidebar-launcher floating-controls" role="toolbar" aria-label="Document library" aria-orientation="vertical"><TipButton ref={sidebarToggle} label="Toggle documents" variant="ghost" size="icon" aria-expanded={sidebarOpen} aria-controls="document-sidebar" onClick={() => toggleSidebar(!sidebarOpen)}><PanelLeft /></TipButton><TipButton label="New document" variant="ghost" size="icon" disabled={snapshot.documentBusy} onClick={() => void editor()?.newDocument()}><FilePlus2 /></TipButton><TipButton label="Open file…" variant="ghost" size="icon" disabled={snapshot.documentBusy} onClick={() => fileRef.current?.click()}><FolderOpen /></TipButton><TipButton ref={objectsToggle} label="Toggle objects" variant="ghost" size="icon" aria-expanded={objectsOpen} aria-controls="objects-sidebar" onClick={() => togglePanel(objectsOpen ? null : 'objects')}><Layers /></TipButton></div>
    <div className="document-actions floating-controls" role="toolbar" aria-label="Document actions"><TipButton label="Undo" shortcut="⌘Z" variant="ghost" size="icon" disabled={!snapshot.canUndo} onClick={() => editor()?.undo()}><Undo2 /></TipButton><TipButton label="Redo" shortcut="⇧⌘Z" variant="ghost" size="icon" disabled={!snapshot.canRedo} onClick={() => editor()?.redo()}><Redo2 /></TipButton><TipButton label="Save" variant="ghost" size="icon" onClick={() => editor()?.saveFile()}><Save /></TipButton>
    <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" aria-label="Export and share" />}><Download /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => editor()?.exportFile("unicode")}>TXT Unicode text</DropdownMenuItem><DropdownMenuItem onClick={() => editor()?.exportFile("ascii")}>ASC ASCII text</DropdownMenuItem><DropdownMenuItem onClick={() => editor()?.exportFile("svg")}>SVG Vector image</DropdownMenuItem><DropdownMenuItem onClick={() => editor()?.exportFile("png")}>PNG Raster image</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={() => void editor()?.copyText()}><Copy />Copy text</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
</div><input ref={fileRef} hidden type="file" accept=".json,.mso,.txt,application/json,text/plain" onChange={e => { const file = e.target.files?.[0]; if (file) void editor()?.loadFile(file); e.currentTarget.value = "" }} /><DocumentSidebar onRename={() => { setTitleDraft(snapshot.title); setRenameOpen(true) }} open={sidebarOpen} snapshot={snapshot} onClose={closeSidebar} onDelete={id => { void editor()?.deleteDocument(id) }} onSelect={id => { void editor()?.openDocument(id); if (window.innerWidth < 760 && id !== snapshot.activeDocumentId) closeSidebar() }} /><div className="tool-palette" role="toolbar" aria-label="Drawing tools">{tools.map((item, i) => <span key={item.tool} className={(i === 2 || i === 5) ? "tool-group-start" : ""}><TipButton label={item.label} shortcut={item.key} aria-pressed={snapshot.tool === item.tool} variant="ghost" size="icon" className={snapshot.tool === item.tool ? "tool-active" : ""} onClick={() => editor()?.setTool(item.tool)}>{item.icon}</TipButton></span>)}</div>
    {snapshot.error && dismissedError !== snapshot.error && <div className="error-banner" role="alert"><span>{snapshot.error}</span><Button variant="ghost" size="icon-xs" aria-label="Dismiss error" onClick={() => setDismissedError(snapshot.error)}><X /></Button></div>}{snapshot.tool === "line" && <div className="tool-hint"><Link2 />{snapshot.status}</div>}<div className="canvas-meta sr-only" aria-live="polite">{snapshot.status}. {snapshot.nodeCount} nodes. {snapshot.edgeCount} connections.</div>
    <div className="zoom-controls"><TipButton label="Zoom out" variant="ghost" size="icon-sm" onClick={() => editor()?.zoomBy(.8)}><ZoomOut /></TipButton><button className="zoom-value" onClick={() => editor()?.fit()} aria-label="Fit diagram">{Math.round(snapshot.zoom * 100)}%</button><TipButton label="Zoom in" variant="ghost" size="icon-sm" onClick={() => editor()?.zoomBy(1.25)}><ZoomIn /></TipButton><TipButton label="Fit diagram" shortcut="F" variant="ghost" size="icon-sm" onClick={() => editor()?.fit()}><LocateFixed /></TipButton></div>
    <Dialog open={renameOpen} onOpenChange={setRenameOpen}><DialogContent><DialogHeader><DialogTitle>Rename document</DialogTitle><DialogDescription>Choose a name for this document.</DialogDescription></DialogHeader><Input autoFocus aria-label="Document title" value={titleDraft} onChange={e => setTitleDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); commitTitle() } }} /><Button onClick={commitTitle}>Rename</Button></DialogContent></Dialog>
    <Dialog><DialogTrigger render={<Button className="help-button" variant="ghost" size="icon-sm" aria-label="Keyboard shortcuts" />}><CircleHelp /></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Keyboard shortcuts</DialogTitle><DialogDescription>Everything you need, without leaving the canvas.</DialogDescription></DialogHeader><div className="shortcut-list">{tools.map(t => <div key={t.tool}><span>{t.icon}{t.label}</span><kbd>{t.key}</kbd></div>)}{[["Add to selection", "Shift + click"], ["Select area", "Drag empty canvas"], ["Select all", "⌘ / Ctrl A"], ["Group", "⌘ / Ctrl G"], ["Ungroup", "⇧ ⌘ / Ctrl G"], ["Duplicate selection", "⌘ / Ctrl D"], ["Undo / Redo", "⌘Z / ⇧⌘Z"], ["Bypass snapping", "Alt + drag"], ["Cancel gesture", "Esc"]].map(([label, key]) => <div key={label}><span>{label}</span><kbd>{key}</kbd></div>)}</div></DialogContent></Dialog>
    {snapshot.selectedCount > 1 && <aside className="selection-panel" aria-label="Selection actions"><span>{snapshot.selectedCount} selected</span><div>
      <TipButton label="Group selection" shortcut="⌘G" variant="ghost" size="icon-sm" disabled={!snapshot.canGroup} onClick={() => editor()?.groupSelection()}><Group /></TipButton>
      <TipButton label="Ungroup selection" shortcut="⇧⌘G" variant="ghost" size="icon-sm" disabled={!snapshot.canUngroup} onClick={() => editor()?.ungroupSelection()}><Ungroup /></TipButton>
      <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label="Align selection" />}><AlignHorizontalJustifyStart /></DropdownMenuTrigger><DropdownMenuContent align="end">{([['left','Align left'],['center','Align horizontal centers'],['right','Align right'],['top','Align top'],['middle','Align vertical centers'],['bottom','Align bottom']] as const).map(([alignment,label]) => <DropdownMenuItem key={alignment} onClick={() => editor()?.alignSelection(alignment)}>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>
      <TipButton label="Duplicate selection" shortcut="⌘D" variant="ghost" size="icon-sm" onClick={() => editor()?.duplicateSelection()}><Copy /></TipButton><TipButton label="Delete selection" variant="ghost" size="icon-sm" onClick={() => editor()?.deleteSelection()}><Trash2 /></TipButton>
    </div></aside>}
    {['pencil', 'eraser', 'fill', 'picker'].includes(snapshot.tool) && <aside className="character-panel" aria-label="Drawing character"><label htmlFor="drawing-character">Character</label><Input id="drawing-character" value={snapshot.drawingCharacter} onChange={e => editor()?.setDrawingCharacter(Array.from(e.target.value).at(-1) ?? '#')} /><div className="character-swatches">{['#', '█', '░', '·', '─', '│', '┼', '○', '*'].map(character => <button key={character} aria-label={`Use character ${character}`} aria-pressed={snapshot.drawingCharacter === character} onClick={() => editor()?.setDrawingCharacter(character)}>{character}</button>)}</div><p>{snapshot.tool === 'picker' ? 'Click a character to sample it.' : snapshot.tool === 'fill' ? 'Click a box to set its background fill.' : snapshot.tool === 'eraser' ? 'Drag across text to erase characters.' : 'Drag to draw. Type a character to change your pencil.'}</p></aside>}
    {<ObjectsPanel open={objectsOpen} nodes={snapshot.objects} selectedId={snapshot.selected?.id} select={id => editor()?.selectObject(id)} update={(id, patch) => editor()?.updateObject(id, patch)} order={direction => editor()?.reorderSelection(direction)} close={() => { togglePanel(null); objectsToggle.current?.focus() }} />}
    {snapshot.selectedEdge && <LineInspector edge={snapshot.selectedEdge} update={patch => editor()?.updateSelectedEdge(patch)} duplicate={() => editor()?.duplicateSelection()} remove={() => editor()?.deleteSelection()} />}
    {snapshot.selected && <NodeInspector key={snapshot.selected.id} node={snapshot.selected} connections={snapshot.connections} update={p => editor()?.updateSelected(p)} updateEdge={(id,l) => editor()?.updateEdge(id,l)} deleteEdge={id => editor()?.deleteEdge(id)} duplicate={() => editor()?.duplicateSelection()} remove={() => editor()?.deleteSelection()} />}</section></main></TooltipProvider>
}
