import { DocumentSidebar } from "./DocumentSidebar"
import { useEffect, useRef, useState, type ReactNode } from "react"
import { AlignHorizontalJustifyStart, Group, Ungroup, Braces, CircleHelp, Copy, Database, Download, FilePlus2, FolderOpen, Frame, Hand, Link2, LocateFixed, PanelLeft, MessageSquareText, MousePointer2, Redo2, Save, Server, Trash2, Undo2, X, ZoomIn, ZoomOut } from "lucide-react"
import { type Editor, type DiagramNode, type EditorSnapshot, type Tool } from "@draw/editor"
import { Button } from "@draw/ui/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@draw/ui/components/ui/dialog"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@draw/ui/components/ui/dropdown-menu"
import { Input } from "@draw/ui/components/ui/input"
import { Textarea } from "@draw/ui/components/ui/textarea"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@draw/ui/components/ui/tooltip"
import { Analytics } from '@vercel/analytics/react'

const initialSnapshot: EditorSnapshot = { documents: [], activeDocumentId: "", documentBusy: true, selectedCount: 0, canGroup: false, canUngroup: false, title: "Untitled diagram", tool: "select", selected: null, nodeCount: 0, edgeCount: 0, connections: [], zoom: 1, canUndo: false, canRedo: false, status: "Starting engine…", error: null }
const tools: Array<{ tool: Tool; label: string; key: string; icon: ReactNode }> = [
  { tool: "select", label: "Select", key: "V", icon: <MousePointer2 /> }, { tool: "pan", label: "Pan", key: "H", icon: <Hand /> }, { tool: "connect", label: "Connect", key: "C", icon: <Link2 /> },
  { tool: "service", label: "Service", key: "S", icon: <Server /> }, { tool: "database", label: "Database", key: "D", icon: <Database /> }, { tool: "queue", label: "Queue", key: "Q", icon: <Braces /> }, { tool: "boundary", label: "Boundary", key: "B", icon: <Frame /> }, { tool: "text", label: "Text", key: "T", icon: <MessageSquareText /> },
]

function TipButton({ label, shortcut, children, ...props }: React.ComponentProps<typeof Button> & { label: string; shortcut?: string }) {
  return <Tooltip><TooltipTrigger render={<Button {...props} aria-label={props["aria-label"] ?? label} />}>{children}</TooltipTrigger><TooltipContent>{label}{shortcut && <kbd>{shortcut}</kbd>}</TooltipContent></Tooltip>
}
type Connection = { id: string; from: string; to: string; label: string }
function ConnectionRow({ connection, update, remove }: { connection: Connection; update: (label: string) => void; remove: () => void }) {
  const [label, setLabel] = useState(connection.label); useEffect(() => setLabel(connection.label), [connection.label])
  const commit = () => { if (label !== connection.label) update(label) }
  return <div className="connection-row"><div className="connection-route"><Link2 />{connection.from.slice(0, 5)} → {connection.to.slice(0, 5)}</div><div className="connection-edit"><Input aria-label={`Connection label ${connection.id}`} value={label} placeholder="Connection label" onChange={e => setLabel(e.target.value)} onBlur={commit} onKeyDown={e => { if (e.key === "Enter") e.currentTarget.blur() }} /><Button variant="ghost" size="icon-sm" aria-label={`Delete connection ${connection.id}`} onClick={remove}><Trash2 /></Button></div></div>
}
function Inspector({ node, connections, update, updateEdge, deleteEdge, duplicate, remove }: { node: DiagramNode; connections: Connection[]; update: (patch: Partial<DiagramNode>) => void; updateEdge: (id: string, label: string) => void; deleteEdge: (id: string) => void; duplicate: () => void; remove: () => void }) {
  const [draft, setDraft] = useState(node); useEffect(() => setDraft(node), [node]); const commit = (field: keyof DiagramNode) => { if (draft[field] !== node[field]) update({ [field]: draft[field] }) }
  return <aside className="inspector-panel" aria-label="Inspector"><div className="inspector-heading"><i />{node.kind}<span>{node.id.slice(0, 7)}</span></div><div className="inspector-content"><label htmlFor="node-label">Label</label><Textarea id="node-label" rows={2} value={draft.label} onChange={e => setDraft({ ...draft, label: e.target.value })} onBlur={() => commit("label")} /><details open><summary>Geometry</summary><div className="field-grid">{(["x", "y", "width", "height"] as const).map(field => <label key={field}><span>{field === "width" ? "W" : field === "height" ? "H" : field.toUpperCase()}</span><Input aria-label={field === "width" ? "W" : field === "height" ? "H" : field.toUpperCase()} type="number" value={draft[field]} onChange={e => setDraft({ ...draft, [field]: Number(e.target.value) })} onBlur={() => commit(field)} onKeyDown={e => { if (e.key === "Enter") e.currentTarget.blur() }} /></label>)}</div></details><details open={connections.length > 0}><summary>Connections <span>{connections.length}</span></summary><div className="connection-list">{connections.map(c => <ConnectionRow key={c.id} connection={c} update={label => updateEdge(c.id, label)} remove={() => deleteEdge(c.id)} />)}</div></details></div><div className="inspector-actions"><TipButton label="Duplicate" shortcut="⌘D" variant="ghost" size="icon-sm" onClick={duplicate}><Copy /></TipButton><TipButton label="Delete" shortcut="⌫" variant="ghost" size="icon-sm" onClick={remove}><Trash2 /></TipButton></div></aside>
}

export default function App() {
  const hostRef = useRef<HTMLDivElement>(null), editorRef = useRef<Editor | null>(null), fileRef = useRef<HTMLInputElement>(null)
  const sidebarToggle = useRef<HTMLButtonElement>(null)
  const [sidebarOpen, setSidebarOpen] = useState(() => { try { return localStorage.getItem('draw-sidebar-open') !== 'false' } catch { return true } })
  const toggleSidebar = (open: boolean) => { setSidebarOpen(open); try { localStorage.setItem('draw-sidebar-open', String(open)) } catch {} }
  const closeSidebar = () => { toggleSidebar(false); sidebarToggle.current?.focus() }
  const [renameOpen, setRenameOpen] = useState(false)
  const [snapshot, setSnapshot] = useState(initialSnapshot), [titleDraft, setTitleDraft] = useState(initialSnapshot.title), [dismissedError, setDismissedError] = useState<string | null>(null)
  useEffect(() => { let disposed = false, instance: Editor | undefined; void import("@draw/editor").then(({ Editor }) => { if (disposed || !hostRef.current) return; instance = new Editor(hostRef.current, { onChange: setSnapshot }); editorRef.current = instance; return instance.ready }).catch(error => { if (!disposed) setSnapshot(s => ({ ...s, status: "Engine unavailable", error: error instanceof Error ? error.message : String(error) })) }); return () => { disposed = true; instance?.destroy(); editorRef.current = null } }, [])
  useEffect(() => setTitleDraft(snapshot.title), [snapshot.title]); useEffect(() => { if (snapshot.error !== dismissedError) setDismissedError(null) }, [snapshot.error])
  const editor = () => editorRef.current, commitTitle = () => { const title = titleDraft.trim() || "Untitled diagram"; setTitleDraft(title); editor()?.setTitle(title); setRenameOpen(false) }
  return <TooltipProvider delay={350}><main className="app-shell"><h1 className="sr-only">{snapshot.title}</h1>
    <section className="workspace"><div className="canvas-host" ref={hostRef} />
    <div className="document-library-surface" data-open={sidebarOpen} aria-hidden="true" /><div className="sidebar-launcher floating-controls" role="toolbar" aria-label="Document library" aria-orientation="vertical"><TipButton ref={sidebarToggle} label="Toggle documents" variant="ghost" size="icon" aria-expanded={sidebarOpen} aria-controls="document-sidebar" onClick={() => toggleSidebar(!sidebarOpen)}><PanelLeft /></TipButton><TipButton label="New document" variant="ghost" size="icon" disabled={snapshot.documentBusy} onClick={() => void editor()?.newDocument()}><FilePlus2 /></TipButton><TipButton label="Open file…" variant="ghost" size="icon" disabled={snapshot.documentBusy} onClick={() => fileRef.current?.click()}><FolderOpen /></TipButton></div>
    <div className="document-actions floating-controls" role="toolbar" aria-label="Document actions"><TipButton label="Undo" shortcut="⌘Z" variant="ghost" size="icon" disabled={!snapshot.canUndo} onClick={() => editor()?.undo()}><Undo2 /></TipButton><TipButton label="Redo" shortcut="⇧⌘Z" variant="ghost" size="icon" disabled={!snapshot.canRedo} onClick={() => editor()?.redo()}><Redo2 /></TipButton><TipButton label="Save" variant="ghost" size="icon" onClick={() => editor()?.saveFile()}><Save /></TipButton>
    <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" aria-label="Export and share" />}><Download /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => editor()?.exportFile("unicode")}>TXT Unicode text</DropdownMenuItem><DropdownMenuItem onClick={() => editor()?.exportFile("ascii")}>ASC ASCII text</DropdownMenuItem><DropdownMenuItem onClick={() => editor()?.exportFile("svg")}>SVG Vector image</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={() => void editor()?.copyText()}><Copy />Copy text</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
</div><input ref={fileRef} hidden type="file" accept=".json,.mso,application/json" onChange={e => { const file = e.target.files?.[0]; if (file) void editor()?.loadFile(file); e.currentTarget.value = "" }} /><DocumentSidebar onRename={() => { setTitleDraft(snapshot.title); setRenameOpen(true) }} open={sidebarOpen} snapshot={snapshot} onClose={closeSidebar} onDelete={id => { void editor()?.deleteDocument(id) }} onSelect={id => { void editor()?.openDocument(id); if (window.innerWidth < 760 && id !== snapshot.activeDocumentId) closeSidebar() }} /><div className="tool-palette" role="toolbar" aria-label="Drawing tools">{tools.map((item, i) => <span key={item.tool} className={i === 3 ? "tool-group-start" : ""}><TipButton label={item.label} shortcut={item.key} aria-pressed={snapshot.tool === item.tool} variant="ghost" size="icon" className={snapshot.tool === item.tool ? "tool-active" : ""} onClick={() => editor()?.setTool(item.tool)}>{item.icon}</TipButton></span>)}</div>
    {snapshot.error && dismissedError !== snapshot.error && <div className="error-banner" role="alert"><span>{snapshot.error}</span><Button variant="ghost" size="icon-xs" aria-label="Dismiss error" onClick={() => setDismissedError(snapshot.error)}><X /></Button></div>}{snapshot.tool === "connect" && <div className="tool-hint"><Link2 />{snapshot.status}</div>}<div className="canvas-meta sr-only" aria-live="polite">{snapshot.status}. {snapshot.nodeCount} nodes. {snapshot.edgeCount} connections.</div>
    <div className="zoom-controls"><TipButton label="Zoom out" variant="ghost" size="icon-sm" onClick={() => editor()?.zoomBy(.8)}><ZoomOut /></TipButton><button className="zoom-value" onClick={() => editor()?.fit()} aria-label="Fit diagram">{Math.round(snapshot.zoom * 100)}%</button><TipButton label="Zoom in" variant="ghost" size="icon-sm" onClick={() => editor()?.zoomBy(1.25)}><ZoomIn /></TipButton><TipButton label="Fit diagram" shortcut="F" variant="ghost" size="icon-sm" onClick={() => editor()?.fit()}><LocateFixed /></TipButton></div>
    <Dialog open={renameOpen} onOpenChange={setRenameOpen}><DialogContent><DialogHeader><DialogTitle>Rename document</DialogTitle><DialogDescription>Choose a name for this document.</DialogDescription></DialogHeader><Input autoFocus aria-label="Document title" value={titleDraft} onChange={e => setTitleDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); commitTitle() } }} /><Button onClick={commitTitle}>Rename</Button></DialogContent></Dialog>
    <Dialog><DialogTrigger render={<Button className="help-button" variant="ghost" size="icon-sm" aria-label="Keyboard shortcuts" />}><CircleHelp /></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Keyboard shortcuts</DialogTitle><DialogDescription>Everything you need, without leaving the canvas.</DialogDescription></DialogHeader><div className="shortcut-list">{tools.map(t => <div key={t.tool}><span>{t.icon}{t.label}</span><kbd>{t.key}</kbd></div>)}{[["Add to selection", "Shift + click"], ["Select area", "Drag empty canvas"], ["Select all", "⌘ / Ctrl A"], ["Group", "⌘ / Ctrl G"], ["Ungroup", "⇧ ⌘ / Ctrl G"], ["Duplicate selection", "⌘ / Ctrl D"], ["Undo / Redo", "⌘Z / ⇧⌘Z"], ["Bypass snapping", "Alt + drag"], ["Cancel gesture", "Esc"]].map(([label, key]) => <div key={label}><span>{label}</span><kbd>{key}</kbd></div>)}</div></DialogContent></Dialog>
    {snapshot.selectedCount > 1 && <aside className="selection-panel" aria-label="Selection actions"><span>{snapshot.selectedCount} selected</span><div>
      <TipButton label="Group selection" shortcut="⌘G" variant="ghost" size="icon-sm" disabled={!snapshot.canGroup} onClick={() => editor()?.groupSelection()}><Group /></TipButton>
      <TipButton label="Ungroup selection" shortcut="⇧⌘G" variant="ghost" size="icon-sm" disabled={!snapshot.canUngroup} onClick={() => editor()?.ungroupSelection()}><Ungroup /></TipButton>
      <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label="Align selection" />}><AlignHorizontalJustifyStart /></DropdownMenuTrigger><DropdownMenuContent align="end">{([['left','Align left'],['center','Align horizontal centers'],['right','Align right'],['top','Align top'],['middle','Align vertical centers'],['bottom','Align bottom']] as const).map(([alignment,label]) => <DropdownMenuItem key={alignment} onClick={() => editor()?.alignSelection(alignment)}>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>
      <TipButton label="Duplicate selection" shortcut="⌘D" variant="ghost" size="icon-sm" onClick={() => editor()?.duplicateSelection()}><Copy /></TipButton><TipButton label="Delete selection" variant="ghost" size="icon-sm" onClick={() => editor()?.deleteSelection()}><Trash2 /></TipButton>
    </div></aside>}
    {snapshot.selected && <Inspector key={snapshot.selected.id} node={snapshot.selected} connections={snapshot.connections} update={p => editor()?.updateSelected(p)} updateEdge={(id,l) => editor()?.updateEdge(id,l)} deleteEdge={id => editor()?.deleteEdge(id)} duplicate={() => editor()?.duplicateSelection()} remove={() => editor()?.deleteSelection()} />}</section></main><Analytics /></TooltipProvider>
}
